#practicing space formating and use of functions
print("Please enter the following:")
print()
adjective = input("adjective: ")
animal = input ("animal: ")
verb = input("verb: ")
exclamation = input("exclamation: ")
adjective2 = input("adjective2: ")
verb1 = input("verb1: ")
#using verb1, verb2 etc to differentiate the instances of the verb
verb2 = input("verb2: ")
verb3 = input("verb3: ")
print()
print("Your story is:")
print()
print("The other day, I got into touble. I was running late for an interview")
print(f'A {adjective} {animal} {verb} on top my roof as I came out to lock my door. "{exclamation.capitalize()}!" not again.But all')
print(f"I could think to do was to {verb1} stones.")
print(f"that caused the monkey to mimick me, but not before it attempted to\n{verb2} down")
print(f"Ah!, my already {adjective2} heart {verb3} for a bit. I ran in,\nbolted my door and peeped from an opening.Was I going to miss my interview?")